# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dde9a0d95182d76771f1e4fe5d2afe81f3af6a0329563570de90b2f8c04778905cdc8a5406080c8f320dd342e0118e0762210746414e07347388894b2b6bfd5f

test:
  secret_key_base: 93989df1ddd91696a8d645e3c59c20121c2acf55fce80ca8b7ef11f450a665a7a41fd237fed6e926c79a02f4cbae17dcac49a42a1e1cb69ec1cfeeb533a9f570

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
